title: News Briefing
description: 每日全球新闻简报
baseurl: ""
url: "https://zj-wpc.github.io"
github:
  repo: zj-wpc/news-briefing

markdown: kramdown
theme: minima
timezone: Asia/Shanghai

# 固定链接格式：/年份/月份/日期/标题.html
permalink: /:year/:month/:day/:title.html

collections:
  posts:
    output: true
